export const educationList = [
"20-20 Open College",
"A.R.T. Medical College Ethiopia",
"AA Science and Technology University",
"Abyssinia College",
"Adadale TVET Institute",
"Adama General Hospital and Medical College",
"Adama Polytechnic Institute",
"Adama Science and Technology University",
"Adama TVET College",
"Adda TVET Institute",
"Addis Ababa Medical College",
"Addis Ababa Polytechnic College",
"Addis Ababa Science and Technology University",
"Addis Ababa University",
"Addis College",
"Addis Continental Public Health Institute",
"Addis Zemen TVET Institute",
"Adigrat Industrial and Construction College",
"Adigrat SDC",
"Adigrat University",
"Admas College",
"Admas University",
"Admas University College",
"Adola Health College",
"Agarfa TVET Institute",
"Agana TVET Institute",
"Agaro TVET Institute",
"Agibe Youth Training Center",
"Aksum Business College",
"Aksum University",
"Akaki TVET College",
"Akesta TVET Institute",
"Aleta Wondo TVET Institute",
"Alelitu College",
"Alkan Health Science College",
"Alkan Medical College",
"Alpha Distance Education University College",
"Alpha University College",
"Ambo TVET College",
"Ambo TVET Institute",
"Ambo University",
"Amdowarek TVET Institute",
"Amigna TVET Institute",
"Amuru TVET Institute",
"Anetse Business and Health College",
"Ankasha Guagusa TVET Institute",
"Arada Giorgis Health Science College",
"Arada Georgis Medical College",
"Arba Minch TVET College",
"Arba Minch University",
"Arba Minch Yesus Technical College",
"Arba Minch Women’s Training Center",
"Arba Minch Teachers College",
"Arsi Negele TVET Institute",
"Arsi Robe TVET Institute",
"Arsi University",
"Asella TVET Institute",
"Asendabo TVET Institute",
"Assosa TVET College",
"Assosa University",
"Atlas Health College",
"Aykel TVET Institute",
"Ayira Nursing School",
"Ayira TVET Institute",
"Ayer Tena Health Science College",
"Badeno TVET Institute",
"Bahir Dar Health Science College",
"Bahir Dar Polytechnic College",
"Bahir Dar TVET College",
"Bahir Dar University",
"Bako Agricultural TVET College",
"Bako TVET Institute",
"Bale Robe TVET Institute",
"Bati TVET Institute",
"Batu Global College",
"Batu Polytechnic Institute",
"Batu Terara TVET Institute",
"Bele TVET Institute",
"Belay Zeleke Health College",
"Beles Health College",
"Ben Meskerem College",
"Berhan International College",
"Bethel Medical College",
"Bethlehem Solidarity College",
"Bichena TVET Institute",
"Bishoftu TVET Institute",
"Biya College",
"Blue Mount College",
"Blue Nile College",
"Boditi TVET Institute",
"Bole TVET Institute",
"Bonga TVET College",
"Bonga University",
"Bore TVET Institute",
"Bruh Tesfa Montessori College",
"Bule Hora University",
"Burayu TVET Institute",
"Burie Agricultural TVET College",
"Butajira TVET College",
"CPU Business and Computer Technology College",
"CPU College",
"Care College",
"Care Medical College",
"Central Health College",
"Central Health Science College",
"Central Medical College",
"Central University College",
"Chagni TVET Institute",
"Chilalo Health Science and Technology College",
"Chole TVET Institute",
"City College",
"Combolcha Agricultural TVET College",
"Dabena TVET College",
"Dadi Abenezer College",
"Dandi Boru College",
"Dandii Boru University College",
"Dangila Andinet Health Science College",
"Dangila TVET Institute",
"Darimu TVET Institute",
"Debark TVET Institute",
"Debark University",
"Debre Birhan Health Science College",
"Debre Birhan TVET College",
"Debre Birhan University",
"Debre Markos Health Science College",
"Debre Markos TVET College",
"Debre Markos University",
"Debre Tabor Health Science College",
"Debre Tabor TVET College",
"Debre Tabor University",
"Debub Ethiopia College",
"Debub Ethiopia College (Aleta Wondo)",
"Debub Ethiopia College (Hawassa)",
"Dedo TVET Institute",
"Dembi Dolo University",
"Deneba TVET Institute",
"Denbosco Technical College",
"Dera TVET Institute",
"Dessie Health Science College",
"Dilla TVET Institute",
"Dilla University",
"Dire Dawa Health College",
"Dire Dawa TVET College",
"Dire Dawa University",
"Dodola TVET Institute",
"Dolo Mena TVET Institute",
"Don Bosco College",
"Dona Berbera TVET Institute",
"Dur Betie TVET Institute",
"Durman College",
"Dynamic International University College",
"ECUSTA Higher Learning Institute",
"Edaga Arbi TVET Institute",
"Edaga Hamus TVET Institute",
"Efa College",
"Ebinat TVET Institute",
"Ethiopian Adventist College",
"Ethiopian Civil Service University",
"Ethiopian National Medical College",
"Ethiopian-Italy TVET College",
"Ethiopis Distance Education College",
"Ethio International Health College",
"Ethio Lence College",
"Ethio Millennium Health and Technology College",
"Ethio National Medical College",
"Ethio-Italy TVET College",
"Ethio-Chinese Polytechnic College",
"Fana Teachers College",
"Fana TVET Institute",
"Fekede Egzi College",
"Fenote Damot TVET Institute",
"Fincha Valley College",
"Finote Selam College",
"Fura College",
"Fura College (Hawassa)",
"Fura College (Yirgalem)",
"Gabist College",
"G8 Engineering College",
"Gage College",
"Gambi College of Medical Science",
"Gambella University",
"Gamo Gofa College",
"Genda Wuha TVET Institute",
"General Paramedical College",
"Genius-Land College",
"Gelemso TVET Institute",
"Gidami TVET Institute",
"Gimbi TVET College",
"Gimbi TVET Institute",
"Ginir TVET Institute",
"Gishe Abay TVET Institute",
"Goba Health College",
"Gobena TVET Institute",
"Gode Agricultural TVET College",
"Gode Nursing College",
"Gondar University",
"Gofa College",
"Gofa Universal College",
"Golden Awash College",
"Gololcha TVET Institute",
"Gonder Health Science College",
"Gonder Teachers College",
"Gonder TVET Institute",
"Gonder University",
"Gonjebe Education and Training College",
"Goro TVET Institute",
"Gotoniyal College",
"Green Land College (Durame)",
"Greenwich College",
"Guba TVET Institute",
"Gudina Fayo College",
"Guduru TVET Institute",
"Gulele TVET Institute",
"Gulo TVET Institute",
"Guna TVET Institute",
"Gurd Shola TVET Institute",
"Hagere Bizen TVET Institute",
"Halaba TVET Institute",
"Hamlin College of Midwifery",
"Harambe College",
"Harar Agro Technical and Technology College",
"Harar Health Science College",
"Harar TVET College",
"Haramaya TVET College",
"Haramaya University",
"Harar Health College",
"Harar Teachers College",
"Harar Women’s College",
"Harar Polytechnic College",
"Harar Science College",
"Harar Business College",
"Harar Medical College",
"Harar Technology College",
"Harar Management College",
"Harar Leadership College",
"Harar Institute of Technology",
"Harar University College",
"Harar Open College",
"Harar Distance College",
"Harar University",
"Haro Sabu TVET Institute",
"Hashenge College",
"Hawassa Health Science College",
"Hawassa TVET College",
"Hawassa University",
"Hawassa Women Development Center",
"Hayat Medical College",
"Hayome Medical College",
"Health Science College (various campuses)",
"Hemisfer Health Science College",
"Higher 4 TVET Institute",
"Higher 7 TVET Institute",
"Higher 12 TVET Institute",
"Higher 20 TVET Institute",
"HiLCoE School of Computer Science and Technology",
"Horn International College",
"Horn International Health College",
"Horizon College",
"Hossana TVET College",
"Hossana Health Science College",
"Hossana Teachers College",
"Hossana Polytechnic College",
"Hossana Business College",
"Hossana Medical College",
"Hossana University College",
"ICU Computer Engineering College",
"IES Health College",
"IES Medical College",
"IES Business College",
"IES Technology College",
"IES Teachers College",
"IES Polytechnic College",
"IES Institute",
"IES University College",
"IES Open College",
"IES Distance College",
"IES Training Center",
"IES Academy",
"IES College",
"IES University",
"IES School",
"IES Center",
"IES Research Institute",
"IES Innovation Institute",
"IES Technology Institute",
"IES Digital Institute",
"IES AI Institute",
"IES Robotics Institute",
"IES Space Institute",
"IES Aviation Institute",
"IES Maritime Institute",
"IES Logistics Institute",
"IES Tourism Institute",
"IES Hospitality Institute",
"IES Fashion Institute",
"IES Design Institute",
"IES Media Institute",
"IES Communication Institute",
"IES Business Institute",
"IES Law Institute",
"IES Health Institute",
"IES Engineering Institute",
"IES Agriculture Institute",
"IES Social Science Institute",
"IES Humanities Institute",
"IES Science Institute",
"IES Polytechnic School",
"IES Technical School",
"IES Vocational School",
"IES Training School",
"IES Research School",
"IES Innovation School",
"IES Leadership School",
"IES Governance School",
"IES Peace School",
"IES Development School",
"IES Technology School",
"IES Digital School",
"IES AI School",
"IES Robotics School",
"IES Space School",
"IES Aviation School",
"IES Maritime School",
"IES Logistics School",
"IES Tourism School",
"IES Hospitality School",
"IES Fashion School",
"IES Design School",
"IES Media School",
"IES Communication School",
"IES Business School",
"IES Law School",
"IES Health School",
"IES Engineering School",
"IES Agriculture School",
"IES Social Science School",
"IES Humanities School",
"IES Science School",
"IES Academy",
"IES Institute",
"IES College",
"IES University",
"IES School",
"IES Center",
"IES Training Center",
"IES Research Center",
"IES Innovation Center",
"IES Technology Center",
"IES Digital Center",
"IES AI Center",
"IES Robotics Center",
"IES Space Center",
"IES Aviation Center",
"IES Maritime Center",
"IES Logistics Center",
"IES Tourism Center",
"IES Hospitality Center",
"IES Fashion Center",
"IES Design Center",
"IES Media Center",
"IES Communication Center",
"IES Business Center",
"IES Law Center",
"IES Health Center",
"IES Engineering Center",
"IES Agriculture Center",
"IES Social Science Center",
"IES Humanities Center",
"IES Science Center",
"IES Polytechnic Institute",
"IES Technical Institute",
"IES Vocational Institute",
"IES Training Institute",
"IES Research Institute",
"IES Innovation Institute",
"IES Leadership Institute",
"IES Governance Institute",
"IES Peace Institute",
"IES Development Institute",
"IES Technology Institute",
"IES Digital Institute",
"IES AI Institute",
"IES Robotics Institute",
"IES Space Institute",
"IES Aviation Institute",
"IES Maritime Institute",
"IES Logistics Institute",
"IES Tourism Institute",
"IES Hospitality Institute",
"IES Fashion Institute",
"IES Design Institute",
"IES Media Institute",
"IES Communication Institute",
"IES Business Institute",
"IES Law Institute",
"IES Health Institute",
"IES Engineering Institute",
"IES Agriculture Institute",
"IES Social Science Institute",
"IES Humanities Institute",
"IES Science Institute",
"IES University College",
"IES National College",
"IES International College",
"IES Global College",
"IES Continental College",
"IES Regional College",
"IES City College",
"IES Metropolitan College",
"Jari TVET Institute",
"Jemma TVET Institute",
"Jiga TVET Institute",
"Jigdan College",
"Jigjiga Health College",
"Jigjiga TVET College",
"Jigjiga University",
"Jima Arjo TVET Institute",
"Jima Medical College",
"Jima Rarie TVET Institute",
"Jimma TVET College",
"Jimma University",
"Jinka Health Science College",
"Jinka TVET Institute",
"Jinka University",
"Joint Vision College",
"Joint Vision Development Studies College",
"Jole TVET Institute",
"Jommo TVET Institute",
"Jote TVET Institute",
"Kachisi TVET Institute",
"Kaliti Leather Industry Institute",
"Kambata TVET Institute",
"Kambata Health Science College",
"Kambata Teachers College",
"Kambata Polytechnic College",
"Kambata Business College",
"Kambata Medical College",
"Kambata University College",
"Kambata TVET Institute",
"Karamara TVET Institute",
"Kelem Technology and Education Institute",
"Kemisie TVET Institute",
"Kea-Med College",
"Kea-Med Medical College",
"Kebri Dehar University",
"Kembata TVET Institute",
"Kembata Health College",
"Kembata Teachers College",
"Kembata Polytechnic College",
"Kembata Business College",
"Kembata Medical College",
"Kembata University College",
"Kembata TVET Institute",
"Kena TVET Institute",
"Kersa TVET Institute",
"Keta TVET Institute",
"Kidist Lideta Medical College",
"Kidist Mariam College",
"Kidist Mariam University College",
"Kiflom TVET Institute",
"Kiflom Health College",
"Kiflom Business College",
"Kiflom Medical College",
"Kiflom Polytechnic College",
"Kiflom Teachers College",
"Kiflom University College",
"Kiflom TVET Institute",
"Kindo TVET Institute",
"Kindo Health College",
"Kindo Business College",
"Kindo Medical College",
"Kindo Polytechnic College",
"Kindo Teachers College",
"Kindo University College",
"Kindo TVET Institute",
"Kofele TVET Institute",
"Kokeb Technical College",
"Kombolcha Agricultural TVET College",
"Kombolcha TVET Institute",
"Konso TVET Institute",
"Koysha TVET Institute",
"Kotebe Metropolitan University",
"Kuku College",
"Kunz College",
"Kuyu TVET Institute",
"Lalibela TVET Institute",
"Lare TVET Institute",
"Lare Health College",
"Lare Business College",
"Lare Medical College",
"Lare Polytechnic College",
"Lare Teachers College",
"Lare University College",
"Lare TVET Institute",
"Lasta TVET Institute",
"Lasta Health College",
"Lasta Business College",
"Lasta Medical College",
"Lasta Polytechnic College",
"Lasta Teachers College",
"Lasta University College",
"Lasta TVET Institute",
"Leadstar International Academy",
"Lemman TVET Institute",
"Lelistu Oromia College",
"Lemi TVET Institute",
"Lemi Health College",
"Lemi Business College",
"Lemi Medical College",
"Lemi Polytechnic College",
"Lemi Teachers College",
"Lemi University College",
"Lemi TVET Institute",
"Lenca TVET Institute",
"Lenca Health College",
"Lenca Business College",
"Lenca Medical College",
"Lenca Polytechnic College",
"Lenca Teachers College",
"Lenca University College",
"Lenca TVET Institute",
"Lode Hitosa TVET Institute",
"Logia TVET Institute",
"Logo Hayk TVET Institute",
"Lucy College",
"Lucy Health College",
"Lucy Medical College",
"Lucy Polytechnic College",
"Lucy Teachers College",
"Lucy University College",
"Lucy TVET Institute",
"Madawalabu University",
"Maichew Agricultural College",
"Maichew Technical College",
"Maichew TVET Institute",
"Maksegnit TVET Institute",
"Maksegnit Health College",
"Maksegnit Business College",
"Maksegnit Medical College",
"Maksegnit Polytechnic College",
"Maksegnit Teachers College",
"Maksegnit University College",
"Maksegnit TVET Institute",
"Maksegnit Training Center",
"Maksegnit Academy",
"Maksegnit College",
"Maksegnit Institute",
"Maksegnit University",
"Maksegnit School",
"Maksegnit Center",
"Maksegnit Research Institute",
"Maksegnit Innovation Institute",
"Maksegnit Technology Institute",
"Maksegnit Digital Institute",
"Maksegnit AI Institute",
"Maksegnit Robotics Institute",
"Maksegnit Space Institute",
"Maksegnit Aviation Institute",
"Maksegnit Maritime Institute",
"Maksegnit Logistics Institute",
"Maksegnit Tourism Institute",
"Maksegnit Hospitality Institute",
"Maksegnit Fashion Institute",
"Maksegnit Design Institute",
"Maksegnit Media Institute",
"Maksegnit Communication Institute",
"Maksegnit Business Institute",
"Maksegnit Law Institute",
"Maksegnit Health Institute",
"Maksegnit Engineering Institute",
"Maksegnit Agriculture Institute",
"Maksegnit Social Science Institute",
"Maksegnit Humanities Institute",
"Maksegnit Science Institute",
"Maksegnit Polytechnic School",
"Maksegnit Technical School",
"Maksegnit Vocational School",
"Maksegnit Training School",
"Maksegnit Research School",
"Maksegnit Innovation School",
"Maksegnit Leadership School",
"Maksegnit Governance School",
"Maksegnit Peace School",
"Maksegnit Development School",
"Maksegnit Technology School",
"Maksegnit Digital School",
"Maksegnit AI School",
"Maksegnit Robotics School",
"Maksegnit Space School",
"Maksegnit Aviation School",
"Maksegnit Maritime School",
"Maksegnit Logistics School",
"Maksegnit Tourism School",
"Maksegnit Hospitality School",
"Maksegnit Fashion School",
"Maksegnit Design School",
"Maksegnit Media School",
"Maksegnit Communication School",
"Maksegnit Business School",
"Maksegnit Law School",
"Maksegnit Health School",
"Maksegnit Engineering School",
"Maksegnit Agriculture School",
"Maksegnit Social Science School",
"Maksegnit Humanities School",
"Maksegnit Science School",
"Maksegnit University College",
"Maksegnit Institute",
"Medco Bio-Medical College",
"Meda Welabu University",
"Mekane Yesus Management and Leadership College",
"Mekdela Amba University",
"Mekelle Institute of Technology",
"Mekelle University",
"Mekelle Garment Training Center",
"Mekelle Health Science College",
"Mekelle Polytechnic College",
"Mekelle TVET Institute",
"Meki TVET Institute",
"Meki Health College",
"Meki Business College",
"Meki Medical College",
"Meki Polytechnic College",
"Meki Teachers College",
"Meki University College",
"Meki TVET Institute",
"Mettu Health Science College",
"Mettu TVET College",
"Mettu University",
"Micro Business College",
"Microlink Information Technology College",
"Mida Woremo TVET Institute",
"Mida Health College",
"Mida Business College",
"Mida Medical College",
"Mida Polytechnic College",
"Mida Teachers College",
"Mida University College",
"Mida TVET Institute",
"Miki Leland College",
"Mishkan College",
"Mishkan Distance Education College",
"Mizan Tepi University",
"Mizan TVET Institute",
"Mizan Health Science College",
"Mizan Business College",
"Mizan Medical College",
"Mizan Polytechnic College",
"Mizan Teachers College",
"Mizan University College",
"Mizan TVET Institute",
"Mulugeta TVET Institute",
"Myungsang Medical College",
"NA Business College",
"Nahu Senay KG TTC",
"National Alfurkan College",
"National College",
"Negele Health Science College",
"Negele TVET Institute",
"Nejo Agricultural College",
"Nejo TVET Institute",
"Nekemte Health College",
"Nekemte TVET College",
"Nekemte TVET Institute",
"New Abissinia College",
"New Century Health Science College",
"New Generation College",
"New Generation University College",
"New Global Vision College",
"New Life Community College",
"New Millennium College",
"New Millennium College (Distance)",
"New Man College",
"New Millenium College",
"New Millenium College (Distance)",
"New Vision College",
"New Vision Health College",
"New Vision Business College",
"New Vision Medical College",
"New Vision Polytechnic College",
"New Vision Teachers College",
"New Vision University College",
"New Vision TVET Institute",
"Nigiste Saba TVET Institute",
"Nile College",
"Nifas Silk TVET College",
"Nire Health College",
"Nire Business College",
"Nire Medical College",
"Nire Polytechnic College",
"Nire Teachers College",
"Nire University College",
"Nire TVET Institute",
"North East Health College",
"Nur Selam College",
"Oda Bultum University",
"Oda Buluk College",
"Oda TVET Institute",
"Oda Health College",
"Oda Business College",
"Oda Medical College",
"Oda Polytechnic College",
"Oda Teachers College",
"Oda University College",
"Oda TVET Institute",
"Omo College",
"Omega Health College",
"Oromia Academic College",
"Oromia College",
"Oromia Public Service College",
"Oromia TVET Institute",
"Oromia Health College",
"Oromia Business College",
"Oromia Medical College",
"Oromia Polytechnic College",
"Oromia Teachers College",
"Oromia University College",
"Oromia TVET Institute",
"Orbit Information College",
"Open 2020 College",
"Open College",
"Openo TVET College",
"Panafric College",
"Paradise Valley College",
"Paramed Health Science College",
"PESC Information Systems College",
"Pharma Health Science College",
"Poly Institute of Technology",
"Polytechnic College (various campuses)",
"Pretor Law College",
"Pride College",
"Professional Health College",
"Project Mercy College",
"Queens College",
"Queen’s Health College",
"Queen’s Medical College",
"Queen’s Business College",
"Queen’s Polytechnic College",
"Queen’s Teachers College",
"Queen’s University College",
"Queen’s TVET Institute",
"Raare TVET Institute",
"Rasa Health College",
"Ras-Dashen Health College",
"Raya University",
"Repi TVET Institute",
"Rift Valley College",
"Rift Valley Medical College",
"Rift Valley University",
"Rift Valley University College",
"Rhobot Medical College",
"Roha College",
"Royal College",
"Royal Health College",
"Royal Medical College",
"Royal Polytechnic College",
"Royal Teachers College",
"Royal University College",
"Rural Development College",
"Saba TVET Institute",
"Salale University",
"Salihom Business College",
"Salihom Health Science College",
"Sante Medical College",
"Sawula TVET Institute",
"Sebeta TVET Institute",
"Secheduna Health College",
"Seamless College of Distance Education",
"Selale University",
"Selam Nursing College",
"Selam Technical College",
"Selam TVET Institute",
"Selihom School of Nursing",
"Selihom Teachers Education and Health College",
"Sena Animal Health College",
"Senafe TVET Institute",
"Setema TVET Institute",
"Shambu TVET College",
"Shashamene Health Science College",
"Shashamene TVET College",
"Sheba Info Tech College",
"Sheba University College",
"Sheger TVET Institute",
"Sheraro TVET Institute",
"Shire Agricultural College",
"Shire SDC",
"Shire TVET Institute",
"Shirka TVET Institute",
"Shola TVET Institute",
"Sibu Sire TVET Institute",
"Sidama Net Business College",
"Sodo Christian Hospital (PAACS Collaboration)",
"Sodo TVET College",
"Soloda Health and Technology College",
"SOS Medical College",
"St. Lideta Health Science College",
"St. Lukas Nursing College",
"St. Mary’s University",
"St. Mary’s University College",
"St. Mary Women’s Training Center",
"St. Paul’s Medical College",
"St. Peter’s Health College",
"St. Peter’s Medical College",
"St. Peter’s University College",
"St. Peter’s TVET Institute",
"Summit College",
"Sun Light Health College",
"Sunshine Business College",
"Tabor TVET Institute",
"Tana Haik College",
"Tasa Roba College",
"Teda Health Science College",
"Tegbareid TVET College",
"Tepi TVET Institute",
"Terefe TVET Institute",
"Tigray Agricultural College",
"Tigray Health Science College",
"Tigray Polytechnic College",
"Tigray Teachers College",
"Tigray University College",
"Tigray TVET Institute",
"Tilahun Yigzaw TVET Institute",
"Tinsae Health College",
"Tinsae Medical College",
"Tinsae Polytechnic College",
"Tinsae Teachers College",
"Tinsae University College",
"Tinsae TVET Institute",
"Tsedal Nega College",
"Tropical College",
"Tropical Health College",
"Tsehay Health College",
"Tsehay Medical College",
"Tsehay Polytechnic College",
"Tsehay Teachers College",
"Tsehay University College",
"Tsehay TVET Institute",
"Tulu Bolo TVET Institute",
"Tulu Health College",
"Tulu Medical College",
"Tulu Polytechnic College",
"Tulu Teachers College",
"Tulu University College",
"Tulu TVET Institute",
"Tulu Wayo TVET Institute",
"Tulu Wayo Health College",
"Tulu Wayo Business College",
"Tulu Wayo Medical College",
"Tulu Wayo Polytechnic College",
"Tulu Wayo Teachers College",
"Tulu Wayo University College",
"Tulu Wayo TVET Institute",
"Tulu Wayo Training Center",
"Tulu Wayo Academy",
"Tulu Wayo Institute",
"Tulu Wayo College",
"Tulu Wayo University",
"Tulu Wayo School",
"Tulu Wayo Center",
"Ude TVET Institute",
"Ude Health College",
"Ude Business College",
"Ude Medical College",
"Ude Polytechnic College",
"Ude Teachers College",
"Ude University College",
"Ude TVET Institute",
"Unity Medical College",
"Unity Polytechnic Institute",
"Unity University",
"Universal College",
"Universal Medical College",
"University of Gondar",
"University of Jigjiga",
"University of Jimma",
"University of Mekelle",
"University of Wachemo",
"University of Wolaita Sodo",
"University of Woldia",
"University of Wolkite",
"University of Wollega",
"University of Wollo",
"US College",
"Victory College",
"Vision Health College",
"Vision Medical College",
"Vision Business College",
"Vision Polytechnic College",
"Vision Teachers College",
"Vision University College",
"Vision TVET Institute",
"Vocational Training Institute (various campuses)",
"Wachemo University",
"Wacha TVET Institute",
"Waka TVET Institute",
"Walaita Sodo University",
"Walaita Sodo TVET College",
"Waldayn TVET Institute",
"Wama Hagalo TVET Institute",
"Wanja TVET Institute",
"Wanjii TVET Institute",
"Washera Broad View College",
"Weldeya TVET Institute",
"Weliso TVET College",
"Welkite University",
"Welkite TVET College",
"Wendo Genet College",
"Wendo Genet TVET Institute",
"Wengelawit TVET Institute",
"Wereilu TVET Institute",
"Western Star College",
"Western University College",
"Woldia University",
"Woldia TVET Institute",
"Wolaita Sodo University",
"Wolaita Sodo TVET Institute",
"Wolayita Teachers Education College",
"Wolayita TVET Institute",
"Wolayita Health Science College",
"Wolayita Business College",
"Wolayita Medical College",
"Wolayita Polytechnic College",
"Wolayita Teachers College",
"Wolayita University College",
"Wolayita TVET Institute",
"Wolkite University",
"Wolkite TVET Institute",
"Wollega University",
"Wollega TVET College",
"Wollo University",
"Wollo TVET Institute",
"Woreda TVET Institute",
"Wuchale Karl Boem Institute",
"Wukro Agricultural College",
"Wukro Health College",
"Wukro Polytechnic College",
"Wukro SDC",
"Wukro St. Mary College",
"Wukro TVET Institute",
"Yabelo TVET Institute",
"Yabello Health College",
"Yabello Business College",
"Yabello Medical College",
"Yabello Polytechnic College",
"Yabello Teachers College",
"Yabello University College",
"Yabello TVET Institute",
"Yared Music School",
"Yardstick International College",
"Yeglad Health College",
"Yeka TVET Institute",
"Yekatit 12 Hospital Medical College",
"Yenegew Sew College",
"Yenegew Sew TVET Institute",
"Yergalem TVET Institute",
"Yifat TVET Institute",
"Yirgalem TVET Institute",
"Yirgalem Health College",
"Yirgalem Business College",
"Yirgalem Medical College",
"Yirgalem Polytechnic College",
"Yirgalem Teachers College",
"Yirgalem University College",
"Yirgalem TVET Institute",
"Yom College",
"Yubdo TVET Institute",
"Zana TVET Institute",
"Zarema TVET Institute",
"Zay TVET Institute",
"Zegie TVET Institute",
"Zegie Health College",
"Zegie Business College",
"Zegie Medical College",
"Zegie Polytechnic College",
"Zegie Teachers College",
"Zegie University College",
"Zegie TVET Institute",
"Zemen Development and Management College",
"Zena TVET Institute",
"Zengena College",
"Zewditu Health College",
"Zewditu Medical College",
"Zewditu Polytechnic College",
"Zewditu Teachers College",
"Zewditu University College",
"Zewditu TVET Institute",
"Zion College",
"Zuma Health Science College",
"Other (Institution Not Listed)",

];

