export const programsByDegree: Record<string, string[]> = {
  "Diploma / Level I–IV (TVET)": [
    "Accounting",
    "Accounting & Budgeting",
    "Accounting & Finance (Diploma)",
    "Administrative Assistance",
    "Advanced Auto Mechanics",
    "Agricultural Extension (TVET)",
    "Agricultural Machinery",
    "Agricultural Marketing",
    "Agriculture (General)",
    "Animal Health",
    "Animal Production",
    "Animal Science (TVET)",
    "Architecture Drafting",
    "Automotive Body Repair",
    "Automotive Electrical Systems",
    "Automotive Engine Maintenance",
    "Automotive Technology",
    "Banking & Finance (Diploma)",
    "Barbering",
    "Basic Computer Maintenance",
    "Beauty Therapy",
    "Biomedical Equipment Maintenance",
    "Building Construction",
    "Business Administration (Diploma)",
    "Business Management (Diploma)",
    "Carpentry & Joinery",
    "Catering & Hospitality",
    "Chemical Laboratory Technology",
    "Child Care & Early Childhood Education",
    "Civil Engineering (TVET)",
    "Clinical Nursing (Diploma)",
    "Clothing & Garment Technology",
    "Computer Hardware Maintenance",
    "Computer Networking",
    "Computer Programming (TVET)",
    "Construction Technology",
    "Culinary Arts",
    "Dairy Technology",
    "Database Administration (TVET)",
    "Drafting Technology",
    "Dry Cleaning & Laundry Technology",
    "Electrical Installation",
    "Electrical Machines Maintenance",
    "Electrical Power Technology (TVET)",
    "Electronics Maintenance",
    "Emergency Medical Technician (EMT)",
    "Environmental Health (Diploma)",
    "Event Management (TVET)",
    "Fashion Design",
    "Film Production (TVET)",
    "Finance & Accounting (Diploma)",
    "Food Preparation & Service",
    "Food Technology (TVET)",
    "Forestry (TVET)",
    "Garment Production",
    "General Mechanics",
    "Graphics Design (TVET)",
    "Hairdressing",
    "Health Extension",
    "Health Information Technology (Diploma)",
    "Hotel Management (Diploma)",
    "Housekeeping Operations",
    "ICT Support Technician",
    "Industrial Electrical Technology",
    "Industrial Metal Fabrication",
    "Information Technology (Diploma)",
    "Interior Design (TVET)",
    "Journalism (TVET)",
    "Laboratory Technology (Diploma)",
    "Leather Technology",
    "Library Science (TVET)",
    "Machine Operation",
    "Masonry",
    "Mechanical Drafting",
    "Metal Work Technology",
    "Midwifery (Diploma)",
    "Milling Technology",
    "Motor Rewinding",
    "Nursing (Diploma)",
    "Office Administration",
    "Occupational Safety & Health (TVET)",
    "Paramedic (Diploma)",
    "Pharmacy Technician",
    "Photography (TVET)",
    "Plumbing",
    "Printing Technology",
    "Radiography (Diploma)",
    "Refrigeration & Air Conditioning",
    "Road Construction Technology",
    "Secretarial Science",
    "Sewing Machine Operation",
    "Software Installation & Support",
    "Solar Technology",
    "Surveying Technology",
    "Tailoring",
    "Tax Accounting (Diploma)",
    "Tourism Operations",
    "Traditional Medicine (TVET)",
    "TV & Radio Maintenance",
    "Veterinary Laboratory Technology (Diploma)",
    "Veterinary Science (TVET)",
    "Welding & Fabrication",
    "Wood Technology",
    "Water Supply Technology",
    "Zero Energy Building Technician (new TVET field)",
    "Other (Program Not Listed)"
  ],

  "Bachelor / BSc / BA / BEd / LLB": [
    "BA in Accounting & Finance",
    "BA in Afan Oromo & Literature",
    "BA in Amharic Language & Literature",
    "BA in Anthropology",
    "BA in Applied Linguistics",
    "BA in Archaeology & Heritage Management",
    "BA in Art & Design",
    "BA in Arts Management",
    "BA in Automotive Engineering (BEng)",
    "BA in Aviation Management",
    "BArch in Architecture",
    "BSc in Aerospace Engineering",
    "BSc in Agribusiness & Value Chain Management",
    "BSc in Agricultural Economics",
    "BSc in Agricultural Engineering",
    "BSc in Agricultural Extension",
    "BSc in Agriculture (General)",
    "BSc in Animal Health",
    "BSc in Animal Science",
    "BSc in Applied Biology",
    "BSc in Applied Chemistry",
    "BSc in Applied Geology",
    "BSc in Applied Mathematics",
    "BSc in Applied Physics",
    "BSc in Aquaculture & Fisheries",
    "BSc in Architecture",
    "BSc in Artificial Intelligence",
    "BSc in Automotive Technology",
    "BA in Banking & Finance",
    "BA in Business Administration",
    "BA in Business Management",
    "BA in Business Law",
    "BA in Business Leadership",
    "BA in Business Information Systems",
    "BEd in Biology",
    "BEd in Chemistry",
    "BEd in Civics",
    "BEd in English Language & Literature",
    "BEd in Geography & Environmental Studies",
    "BEd in History & Heritage Management",
    "BEd in Mathematics",
    "BEd in Physics",
    "BFA in Fine Arts",
    "BSc in Biochemistry",
    "BSc in Biomedical Engineering",
    "BSc in Biology",
    "BSc in Biotechnology",
    "BSc in Botany",
    "BSc in Building Construction Technology",
    "BSc in Business Information Technology",
    "BA in Communication & Media Studies",
    "BA in Community Development",
    "BA in Conflict Resolution",
    "BA in Counseling Psychology",
    "BSc in Chemical Engineering",
    "BSc in Chemistry",
    "BSc in Civil Engineering",
    "BSc in Clinical Laboratory Science",
    "BSc in Clinical Nursing",
    "BSc in Clinical Pharmacy",
    "BSc in Computer Engineering",
    "BSc in Computer Science",
    "BSc in Construction Engineering",
    "BSc in Crop Production",
    "BSc in Cybersecurity",
    "BA in Development Economics",
    "BA in Development Studies",
    "BA in Digital Communication",
    "BSc in Dairy Science",
    "BSc in Data Science",
    "BSc in Dentistry (DDM)",
    "BSc in Dietetics",
    "BSc in Disaster Risk Management",
    "BSc in Dryland Agriculture",
    "BA in Economics",
    "BA in Educational Planning & Management",
    "BA in English Language & Literature",
    "BA in Environmental Studies",
    "BEd in Early Childhood Education",
    "BSc in Electrical & Computer Engineering",
    "BSc in Electrical Engineering",
    "BSc in Electronics Engineering",
    "BSc in Emergency & Critical Care Nursing",
    "BSc in Environmental Health",
    "BSc in Environmental Science",
    "BSc in Epidemiology (Undergrad Track)",
    "BA in Film & Media",
    "BA in Folklore & Cultural Studies",
    "BA in French Language",
    "BSc in Fashion Design & Textile Engineering",
    "BSc in Food Science & Post-Harvest Technology",
    "BSc in Forestry",
    "BSc in Forensic Science",
    "BA in Geography & Environmental Studies",
    "BA in Gender Studies",
    "BA in Governance & Development Studies",
    "BA in Graphic Design",
    "BSc in Geology",
    "BSc in Geophysics",
    "BSc in GIS & Remote Sensing",
    "BA in History & Heritage Management",
    "BA in Hospitality & Tourism Management",
    "BA in Human Resource Management",
    "BSc in Health Information Technology",
    "BSc in Health Officer (Public Health)",
    "BSc in Horticulture",
    "BSc in Hydraulics & Water Resources Engineering",
    "BA in International Relations",
    "BA in Indigenous Knowledge Systems",
    "BSc in Industrial Chemistry",
    "BSc in Industrial Engineering",
    "BSc in Information Science",
    "BSc in Information Technology",
    "BSc in Integrated Emergency Surgery (rare)",
    "BSc in Irrigation Engineering",
    "BA in Journalism & Communication",
    "BA in Land Administration",
    "BA in Language Studies",
    "BA in Leadership & Governance",
    "LLB in Law",
    "BSc in Laboratory Technology",
    "BSc in Land Resource Management",
    "BA in Management",
    "BA in Marketing Management",
    "BA in Music",
    "BEd in Mathematics",
    "BSc in Material Science & Engineering",
    "BSc in Mechanical Engineering",
    "BSc in Mechatronics Engineering",
    "BSc in Medical Laboratory Science",
    "BSc in Medical Radiology Technology",
    "BSc in Medicine (MD)",
    "BSc in Metallurgical Engineering",
    "BSc in Midwifery",
    "BSc in Mining Engineering",
    "BA in Natural Resource Management",
    "BA in Nutrition & Dietetics",
    "BSc in Natural Resource Management",
    "BSc in Neonatal Nursing",
    "BSc in Network Engineering",
    "BSc in Nursing",
    "BA in Oromo Folklore & Literature",
    "BA in Organizational Leadership",
    "BSc in Occupational Health & Safety",
    "BSc in Optometry",
    "BSc in Operation Theatre Nursing",
    "BA in Peace & Conflict Studies",
    "BA in Philosophy",
    "BA in Political Science & International Relations",
    "BA in Project Management",
    "BSc in Parasitology (rare undergrad)",
    "BSc in Petroleum Engineering",
    "BSc in Pharmacy",
    "BSc in Physics",
    "BSc in Physiotherapy",
    "BSc in Plant Science",
    "BSc in Psychology (BSc or BA)",
    "BSc in Public Health",
    "BA in Religious Studies",
    "BA in Rural Development",
    "BSc in Radiology Technology",
    "BSc in Renewable Energy Engineering",
    "BSc in Road & Transport Engineering",
    "BA in Social Anthropology",
    "BA in Social Work",
    "BA in Sociology",
    "BA in Special Needs & Inclusive Education",
    "BA in Sport Science (BEd or BSc)",
    "BA in Statistics (BA or BSc)",
    "BSc in Software Engineering",
    "BSc in Soil Science",
    "BSc in Statistics",
    "BSc in Structural Engineering",
    "BSc in Supply Chain & Logistics Management",
    "BSc in Surveying Engineering",
    "BA in Theatre Arts",
    "BA in Tourism Management",
    "BA in Translation & Interpretation",
    "BSc in Textile Engineering",
    "BSc in Thermal Engineering",
    "BSc in Transport Engineering",
    "BA in Visual Arts",
    "BSc in Veterinary Laboratory Technology",
    "BSc in Veterinary Medicine (DVM)",
    "BA in Water Resource Management",
    "BSc in Water Supply & Environmental Engineering",
    "BSc in Wildlife Management",
    "BA in Zoology",
    "BSc in Zoological Sciences",
    "Other (Program Not Listed)"
  ],

  "Master / MSc / MA / MPH / MBA / MEd / LLM": [
    "MA in Accounting & Finance",
    "MA in Adult Education",
    "MA in Afan Oromo & Literature",
    "MA in Agricultural Communication & Innovation",
    "MA in Agricultural Economics",
    "MA in Amharic Language & Literature",
    "MA in Applied Linguistics",
    "MA in Applied Linguistics & Communication",
    "MA in Applied Sociology",
    "MA in Archaeology & Heritage Management",
    "MA in Art Education",
    "MA in Arts Management",
    "MSc in Adult Health Nursing",
    "MSc in Advanced Clinical Nursing",
    "MSc in Aerospace Engineering",
    "MSc in Agricultural Biotechnology",
    "MSc in Agricultural Economics",
    "MSc in Agricultural Engineering",
    "MSc in Agricultural Entomology",
    "MSc in Agricultural Extension",
    "MSc in Agribusiness & Value Chain Management",
    "MSc in Agronomy",
    "MSc in Analytical Chemistry",
    "MSc in Animal Breeding & Genetics",
    "MSc in Animal Nutrition",
    "MSc in Animal Production",
    "MSc in Anthropology (Applied)",
    "MSc in Applied Ecology",
    "MSc in Applied Entomology",
    "MSc in Applied Microbiology",
    "MSc in Aquaculture & Fisheries Management",
    "MSc in Architecture (Advanced Architectural Design)",
    "MSc in Artificial Intelligence",
    "MSc in Automotive Engineering",
    "MA in Banking & Finance",
    "MA in Behavioral Science",
    "MA in Biblical & Theological Studies",
    "MA in Broadcast Journalism",
    "MSc in Biochemical Engineering",
    "MSc in Biochemistry",
    "MSc in Bioinformatics",
    "MSc in Biomedical Engineering",
    "MSc in Biomedical Imaging",
    "MSc in Biostatistics",
    "MSc in Botanical Sciences",
    "MSc in Business Analytics",
    "MBA in Business Administration",
    "MBA in Business Leadership",
    "MA in Civics & Ethical Studies",
    "MA in Clinical Psychology",
    "MA in Communication Studies",
    "MA in Comparative Literature",
    "MA in Conflict Resolution & Peacebuilding",
    "MA in Counseling Psychology",
    "MSc in Ceramic Engineering",
    "MSc in Chemical Engineering",
    "MSc in Chemistry (Analytical, Organic, Physical, Inorganic)",
    "MSc in Civil Engineering",
    "MSc in Clinical Anatomy",
    "MSc in Clinical Anesthesia",
    "MSc in Clinical Laboratory Science (Chemistry, Hematology, Immunology, Management)",
    "MSc in Clinical Midwifery",
    "MSc in Clinical Pharmacy",
    "MSc in Clinical Psychiatry",
    "MSc in Communication Engineering",
    "MSc in Computer Networking",
    "MSc in Computer Science",
    "MSc in Construction Engineering & Management",
    "MSc in Control & Instrumentation Engineering",
    "MSc in Crop Protection",
    "MSc in Cybersecurity",
    "MA in Development Economics",
    "MA in Development Management",
    "MA in Development Sociology",
    "MA in Digital Communication",
    "MSc in Dairy Science & Technology",
    "MSc in Data Science",
    "MSc in Dermatovenerology (Clinical Specialty)",
    "MSc in Dietetics",
    "MSc in Disaster Risk Management",
    "MSc in Dryland Agriculture",
    "MA in Early Childhood Education",
    "MA in Economics",
    "MA in Educational Leadership",
    "MA in Educational Planning & Management",
    "MA in Educational Psychology",
    "MA in English Language Teaching (TEFL)",
    "MA in Environmental Studies",
    "MSc in Electrical & Computer Engineering",
    "MSc in Electrical Power Engineering",
    "MSc in Electronics Engineering",
    "MSc in Emergency & Critical Care Nursing",
    "MSc in Endodontics (Specialty)",
    "MSc in Engineering Management",
    "MSc in Environmental Chemistry",
    "MSc in Environmental Engineering",
    "MSc in Environmental Health Science",
    "MSc in Environmental Science & Technology",
    "MSc in Epidemiology (MPH or MSc)",
    "MPH in Epidemiology",
    "MPH in Environmental Health",
    "MPH in Field Epidemiology",
    "MPH in General Public Health",
    "MPH in Health Economics",
    "MPH in Health Monitoring & Evaluation",
    "MPH in Health Promotion & Behavior",
    "MPH in Health Systems Management",
    "MA in Film & Media Studies",
    "MA in Folklore & Cultural Studies",
    "MSc in Finance & Investment",
    "MSc in Food Engineering",
    "MSc in Food Safety & Quality",
    "MSc in Food Science & Technology",
    "MSc in Forestry",
    "MSc in Forensic Science",
    "MA in Gender Studies",
    "MA in Geography & Environmental Studies",
    "MA in Governance & Development Studies",
    "MA in Gadaa Studies",
    "MSc in Geotechnical Engineering",
    "MSc in GIS & Remote Sensing",
    "MSc in Global Health",
    "MSc in Gynecology & Obstetrics (Specialty)",
    "MA in History",
    "MA in Human Resource Management",
    "MSc in Health Informatics",
    "MSc in Healthcare Technology Engineering & Management",
    "MSc in Hematology & Immunohematology",
    "MSc in Highway Engineering",
    "MSc in Horticulture",
    "MSc in Human Nutrition",
    "MA in Intercultural Communication",
    "MA in International Relations",
    "MSc in Industrial Chemistry",
    "MSc in Industrial Engineering",
    "MSc in Information Science",
    "MSc in Information Technology",
    "MSc in Integrated Clinical & Community Mental Health",
    "MSc in Integrated Pest Management",
    "MSc in Irrigation Engineering",
    "MA in Land Resource Management",
    "MA in Language Planning & Policy",
    "MA in Leadership & Governance",
    "LLM in Commercial & Investment Law",
    "LLM in Human Rights & Criminal Law",
    "MSc in Land Use Planning & Management",
    "MSc in Livestock Production & Management",
    "MA in Management",
    "MA in Marketing Management",
    "MA in Media & Communication",
    "MA in Music",
    "MSc in Manufacturing Engineering",
    "MSc in Material Science Engineering",
    "MSc in Mechanical Engineering",
    "MSc in Mechanical Systems Design",
    "MSc in Mechatronics Engineering",
    "MSc in Medical Microbiology",
    "MSc in Medical Parasitology",
    "MSc in Medical Physiology",
    "MSc in Metallurgy Engineering",
    "MSc in Midwifery Education",
    "MSc in Molecular Biology",
    "MSc in Monitoring & Evaluation",
    "MSc in Multimedia Technology",
    "MA in Natural Resource Management",
    "MSc in Nano Technology",
    "MSc in Neonatal Nursing",
    "MSc in Network Engineering",
    "MSc in Nutrition & Dietetics",
    "MA in Oromo Folklore & Literature",
    "MA in Organizational Leadership",
    "MSc in Oncology (Clinical Specialty)",
    "MSc in Ophthalmology (Specialty)",
    "MSc in Orthopedics & Traumatology (Specialty)",
    "MA in Peace & Conflict Studies",
    "MA in Philosophy",
    "MA in Political Science & International Relations",
    "MA in Project Management",
    "MA in Psychology",
    "MSc in Parasitology",
    "MSc in Pediatrics & Child Health Nursing",
    "MSc in Pharmaceutical Quality Assurance",
    "MSc in Pharmaceutical Supply Chain Management",
    "MSc in Pharmaceutics",
    "MSc in Pharmacology",
    "MSc in Physics (Condensed Matter, Astrophysics, etc.)",
    "MSc in Plant Breeding",
    "MSc in Plant Biotechnology",
    "MSc in Plant Pathology",
    "MSc in Postharvest Management",
    "MSc in Process Engineering",
    "MSc in Public Health (MPH)",
    "MA in Religious Studies",
    "MA in Rural Development",
    "MSc in Radiology (Specialty)",
    "MSc in Renewable Energy Engineering",
    "MSc in Road & Transport Engineering",
    "MA in Social Anthropology",
    "MA in Social Psychology",
    "MA in Social Work (MSW)",
    "MA in Sociology",
    "MA in Special Needs Education",
    "MA in Sport Management",
    "MSc in Soil Science",
    "MSc in Software Engineering",
    "MSc in Statistics",
    "MSc in Structural Engineering",
    "MSc in Sustainable Energy Engineering",
    "MSc in Surgery (Specialty)",
    "MA in Teaching English as a Foreign Language (TEFL)",
    "MA in Theatre Arts",
    "MA in Tourism Management",
    "MSc in Textile Engineering",
    "MSc in Thermal Systems Engineering",
    "MSc in Transport Economics",
    "MSc in Tropical & Infectious Diseases",
    "MSc in Veterinary Epidemiology",
    "MSc in Veterinary Microbiology",
    "MSc in Veterinary Pathology",
    "MSc in Veterinary Public Health",
    "MSc in Veterinary Surgery",
    "MA in Wildlife Conservation",
    "MSc in Water Resource Engineering",
    "MSc in Watershed Management",
    "MSc in Weed Science",
    "MSc in Wildlife Ecology & Management",
    "Other (Program Not Listed)"
  ],

  "PhD / Doctoral": [
    "PhD in Accounting & Finance",
    "PhD in Adult Education",
    "PhD in Afan Oromo Linguistics",
    "PhD in Agricultural Economics",
    "PhD in Agricultural Engineering",
    "PhD in Agricultural Entomology",
    "PhD in Agricultural Extension",
    "PhD in Agronomy",
    "PhD in Animal Breeding & Genetics",
    "PhD in Animal Nutrition",
    "PhD in Animal Production",
    "PhD in Applied Ecology",
    "PhD in Applied Microbiology",
    "PhD in Aquaculture & Fisheries Management",
    "PhD in Architecture & Urban Planning",
    "PhD in Artificial Intelligence",
    "PhD in Atmospheric Science",
    "PhD in Biochemistry",
    "PhD in Bioinformatics",
    "PhD in Biomedical Engineering",
    "PhD in Biomedical Sciences",
    "PhD in Biostatistics",
    "PhD in Botany",
    "PhD in Business Administration (DBA)",
    "PhD in Business Leadership",
    "PhD in Ceramic Engineering",
    "PhD in Chemical Engineering",
    "PhD in Chemistry (Analytical, Organic, Physical, Inorganic)",
    "PhD in Civil Engineering",
    "PhD in Climate Change & Adaptation",
    "PhD in Clinical Psychology",
    "PhD in Communication Engineering",
    "PhD in Comparative Literature",
    "PhD in Computer Engineering",
    "PhD in Computer Science",
    "PhD in Condensed Matter Physics",
    "PhD in Construction Engineering & Management",
    "PhD in Crop Protection",
    "PhD in Dairy Science & Technology",
    "PhD in Data Science",
    "PhD in Development Economics",
    "PhD in Development Studies",
    "PhD in Digital Communication",
    "PhD in Disaster Risk Management",
    "PhD in Dryland Agriculture",
    "PhD in Ecology & Systematic Zoology",
    "PhD in Ecotourism & Protected Area Management",
    "PhD in Education (Curriculum & Instruction)",
    "PhD in Educational Leadership & Policy Studies",
    "PhD in Electrical & Computer Engineering",
    "PhD in Electrical Power Engineering",
    "PhD in Electronics Engineering",
    "PhD in Emergency & Critical Care Medicine",
    "PhD in Endocrinology (Clinical)",
    "PhD in Energy Economics",
    "PhD in Engineering Management",
    "PhD in English Language Teaching (TEFL)",
    "PhD in Environmental Chemistry",
    "PhD in Environmental Engineering",
    "PhD in Environmental Health",
    "PhD in Environmental Science",
    "PhD in Epidemiology",
    "DrPH in Public Health",
    "PhD in Finance",
    "PhD in Food Science & Technology",
    "PhD in Forestry",
    "PhD in Freshwater Ecology",
    "PhD in Gadaa Studies",
    "PhD in Gender Studies",
    "PhD in Geography & Environmental Studies",
    "PhD in Geology",
    "PhD in Geotechnical Engineering",
    "PhD in GIS & Remote Sensing",
    "PhD in Governance & Development Studies",
    "PhD in Health Communication & Behavior",
    "PhD in Health Economics",
    "PhD in Health Systems & Policy",
    "PhD in History",
    "PhD in Horticulture",
    "PhD in Human Nutrition",
    "PhD in Hydraulics & Water Resources Engineering",
    "PhD in Industrial Chemistry",
    "PhD in Industrial Engineering",
    "PhD in Information Science",
    "PhD in Information Technology",
    "PhD in Innovation & Entrepreneurship",
    "PhD in Inorganic Chemistry",
    "PhD in Irrigation Engineering",
    "PhD in Land Resource Management",
    "PhD in Law (PhD in Legal Studies)",
    "PhD in Leadership & Governance",
    "PhD in Linguistics",
    "PhD in Literature",
    "PhD in Management (General)",
    "PhD in Management (Human Resource Management)",
    "PhD in Management (Marketing Management)",
    "PhD in Manufacturing Engineering",
    "PhD in Material Science Engineering",
    "PhD in Mathematics (Analysis)",
    "PhD in Mathematics (Differential Equations)",
    "PhD in Mathematics (Numerical Analysis)",
    "PhD in Mechanical Design Engineering",
    "PhD in Mechanical Engineering",
    "PhD in Mechatronics Engineering",
    "PhD in Medical Microbiology",
    "PhD in Medical Physiology",
    "PhD in Metallurgy Engineering",
    "PhD in Midwifery & Women’s Health",
    "PhD in Molecular Biology",
    "PhD in Monitoring & Evaluation",
    "PhD in Natural Resource Management",
    "PhD in Nano Technology",
    "PhD in Neuroscience",
    "PhD in Nursing",
    "PhD in Nutrition & Dietetics",
    "PhD in Oncology",
    "PhD in Ophthalmology",
    "PhD in Organizational Leadership",
    "PhD in Parasitology",
    "PhD in Pediatrics & Child Health",
    "PhD in Pharmaceutical Sciences",
    "PhD in Pharmacology",
    "PhD in Philosophy",
    "PhD in Physics (Condensed Matter, Astrophysics, Nuclear Physics)",
    "PhD in Plant Breeding",
    "PhD in Plant Biotechnology",
    "PhD in Plant Ecology",
    "PhD in Plant Pathology",
    "PhD in Political Science & International Relations",
    "PhD in Project Management",
    "PhD in Psychology (Educational, Counseling, Clinical)",
    "PhD in Public Administration",
    "PhD in Public Health (DrPH)",
    "PhD in Radiology",
    "PhD in Renewable Energy Engineering",
    "PhD in Reproductive Health",
    "PhD in Road & Transport Engineering",
    "PhD in Rural Development & Agricultural Extension",
    "PhD in Social Anthropology",
    "PhD in Social Psychology",
    "PhD in Social Work",
    "PhD in Sociology",
    "PhD in Soil Science",
    "PhD in Software Engineering",
    "PhD in Statistics",
    "PhD in Structural Engineering",
    "PhD in Sustainable Energy Engineering",
    "PhD in Surgery (Clinical)",
    "PhD in Teaching English as a Foreign Language (TEFL)",
    "PhD in Textile Engineering",
    "PhD in Thermal Systems Engineering",
    "PhD in Tourism Management",
    "PhD in Transport Economics",
    "PhD in Tropical & Infectious Diseases",
    "PhD in Veterinary Epidemiology",
    "PhD in Veterinary Microbiology",
    "PhD in Veterinary Pathology",
    "PhD in Veterinary Public Health",
    "PhD in Veterinary Surgery",
    "PhD in Water Resource Engineering",
    "PhD in Watershed Management",
    "PhD in Weed Science",
    "PhD in Wildlife Ecology & Management",
    "Other (Program Not Listed)"
  ]
};

export const DEGREE_LEVELS = Object.keys(programsByDegree);
