export const SKILL_CATEGORIES: { category: string; skills: string[] }[] = [
    {
        category: "Technical & Digital Skills",
        skills: [
            "Software development",
            "Web development",
            "Mobile development",
            "Database management",
            "Cloud computing",
            "Cybersecurity",
            "Networking",
            "DevOps",
            "Data analysis",
            "Data science",
            "Machine learning",
            "AI engineering",
            "UI/UX design",
            "Product design",
            "QA testing",
            "IT support",
            "ERP systems (SAP, Oracle, etc.)",
            "CRM systems (Salesforce, HubSpot)",
            "Blockchain",
            "Robotics",
            "Automation tools",
            "GIS systems",
            "CAD design",
            "Digital marketing",
            "SEO/SEM",
            "Social media management",
            "Content management systems",
            "Video editing",
            "Graphic design",
            "Office productivity tools (Excel, Word, PowerPoint)",
        ],
    },
    {
        category: "Business & Management Skills",
        skills: [
            "Project management",
            "Program management",
            "Strategic planning",
            "Business analysis",
            "Operations management",
            "Supply chain management",
            "Procurement",
            "Logistics",
            "Risk management",
            "Quality assurance",
            "Change management",
            "Product management",
            "Business development",
            "Sales strategy",
            "Negotiation",
            "Customer relationship management",
            "Financial analysis",
            "Budgeting",
            "Accounting",
            "Auditing",
            "Human resources management",
            "Talent acquisition",
            "Training & development",
            "Performance management",
        ],
    },
    {
        category: "Soft Skills (Transferable)",
        skills: [
            "Communication",
            "Leadership",
            "Teamwork",
            "Problem-solving",
            "Critical thinking",
            "Creativity",
            "Adaptability",
            "Time management",
            "Emotional intelligence",
            "Conflict resolution",
            "Decision-making",
            "Attention to detail",
            "Work ethic",
            "Collaboration",
            "Presentation skills",
            "Multitasking",
            "Analytical thinking",
            "Interpersonal skills",
        ],
    },
    {
        category: "Industry-Specific Skills",
        skills: [
            "Mechanical engineering",
            "Electrical engineering",
            "Civil engineering",
            "Chemical engineering",
            "Industrial engineering",
            "Structural analysis",
            "Manufacturing processes",
            "Patient care",
            "Medical diagnostics",
            "Nursing procedures",
            "Pharmacy operations",
            "Laboratory analysis",
            "Medical equipment handling",
            "Curriculum development",
            "Classroom management",
            "Instructional design",
            "Assessment & evaluation",
            "Credit analysis",
            "Loan processing",
            "Financial modeling",
            "Investment analysis",
            "Site supervision",
            "Blueprint reading",
            "Quantity surveying",
            "Safety compliance",
            "Food service",
            "Housekeeping",
            "Guest relations",
            "Event management",
            "Crop management",
            "Livestock management",
            "Irrigation systems",
            "Farm machinery operation",
        ],
    },
    {
        category: "Language Skills",
        skills: ["English", "Amharic", "Afaan Oromo", "Tigrinya", "Arabic", "French", "Chinese", "Spanish", "Other"],
    },
    {
        category: "Tools & Software Skills",
        skills: [
            "Python",
            "Java",
            "JavaScript",
            "C#",
            "SQL",
            "R",
            "MATLAB",
            "AutoCAD",
            "Revit",
            "Adobe Photoshop",
            "Adobe Illustrator",
            "Figma",
            "Sketch",
            "Tableau",
            "Power BI",
            "Excel (advanced)",
            "QuickBooks",
            "SPSS",
            "Jira",
            "Trello",
            "Asana",
            "Git/GitHub",
        ],
    },
    {
        category: "Certifications",
        skills: [
            "PMP",
            "PRINCE2",
            "AWS certifications",
            "Google Cloud certifications",
            "Cisco (CCNA, CCNP)",
            "Microsoft Azure",
            "CompTIA (A+, Security+)",
            "CPA",
            "CFA",
            "Teaching certifications",
            "First aid/CPR",
        ],
    },
];

export const FLAT_SKILLS: string[] = SKILL_CATEGORIES.reduce<string[]>((acc, grp) => {
    grp.skills.forEach((s) => acc.push(s));
    return acc;
}, []);

export default SKILL_CATEGORIES;
